#!/usr/bin/env bash

# configs
source config/base
source "config/${user[packages_config]}"

# functions
source archlinux/shell

# arch installer
source archlinux/base
source archlinux/system

# backup
source archlinux/backup

# display help when no arguments passed
[[ $# -eq 0 ]] && archManagerHelp

# parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        # install archlinux
        -ib | --install-base)   section="base"   ;;
        -is | --install-system) section="system" ;;

        # backup export
        -be | --backup-export)
            # display help when no arguments passed
            grep -qi false <<< $(isExist "$2") && {
                message "$yellow$2 ${important}backup paths file not exist{norm}!\n"
                archManagerHelp
            }

            section="exportBackup '$2'"

            shift
        ;;

        # backup import
        -bi | --backup-import)
            # display help when no arguments passed
            grep -qi false <<< $(isExist "$2") && {
                message "$yellow$2 ${important}backup path directory not exist{norm}!\n"
                archManagerHelp
            }

            section="importBackup '$2'"

            shift
        ;;

        # other options
        -d | --debug)  options[debug]=true  ;;
        -h | --help)   archManagerHelp      ;;
        *)             archManagerHelp "$1" ;;
    esac

    shift # next argument
done

# execute section function
eval "$section"
