#!/usr/bin/env bash

function copy() {
    local src="$1"
    local dest="$2"

    cmd "cp -r --parents '$src' '$dest'"
}

function isExist(){
    local path="$(sed "s|^~/|$HOME/|" <<< "$1")"

    if [ -e "$path" ]; then
        echo true
    else
        echo false
    fi
}

function loadPaths(){

    local backupPaths="$1"

    # check paths
    while IFS= read -r line; do
        # skip comments, empty lines
        grep -qE "(^#|^$)" <<< "$line" && continue

        # absolute path
        local path="$(sed "s|^~/|$HOME/|" <<< $line)"

        # check if paths exist
        if grep -qi true <<< $(isExist "$path"); then
            # existing path
            message "${green}[Loaded]$red ==> {norm}$line"

            paths="$paths$path,"
            let loaded++
        else
            # non-existing path
            message "${red}[Error ] ==> $yellow$line ${important}path not exist!"

            let error++
        fi

    done < "$backupPaths"

    paths="$(sed "s|,$||" <<< "${paths[@]}")"


}

function exportBackup() {
    local backupPaths="$1"
    local backupDir="${backup[dir]}/${backup[export_format]}"
    local loaded=0
    local error=0
    local paths

    # load paths
    loadPaths "$backupPaths"

    # export info
    newline_sep
    message "destination path: $cyan$backupDir"
    message "not exists paths: $red$error"
    message "loaded paths: $green$loaded"
    newline

    grep -qi false <<< "$(YN "${cyan}do you want to export loaded paths")" && return
    newline_sep

    # export configs
    cmd "mkdir -p '$backupDir'"

    local IFS=','

    savedColor="$cmdColor"
    cmdColor="$yellow"

    for path in ${paths[@]};do
        copy "$path" "$backupDir/"
    done

    cmdColor="$savedColor"
}
